### ISSUE TITLE
Question: Typescript + Preact

### ISSUE THREAD

**Issue by bykbtzr** [barbuza/typescript-webpack-preact-experiment#1]
You got really good results here...
![bravo](https://cloud.githubusercontent.com/assets/1047033/19501534/3200d8e2-9585-11e6-9a37-60e2db1ea2ab.png)

I think this combination is really powerful and I'm considering to use it as a main stack for my next projects. Have you been using it lately, did you have any problems?!

Thanks))

**Comment by barbuza** [comment]
This is an experiment, but all it's parts are widely used and considered to be stable enough for production use. If your project is big enough in terms of amount of code you may want to switch to react, cause it's size would be relatively small to your own code. However if you really want to make it as small as possible - use this stack and avoid adding lodash.

**Comment by bykbtzr** [comment]
Maybe [lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin) can be added to help with lodash size.

Thanks for the tips ^_^
